## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
env:
  global:
    - PYTHON=conda
before_script:
  - julia --project -e 'import Pkg; Pkg.clone("https://github.com/schmrlng/DifferentialDynamicsModels.jl.git")'
after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'